### ISSUE TITLE
Proposal: Add HTTP and HTTPS listeners

### ISSUE THREAD

**Issue by chrisshiplet** [synapsestudios/terraform-aws-alb#1]
I think it would be reasonable (even if a bit opinionated) to encapsulate our main two listeners into this module as well since I can't really think of a project that we didn't configure this way. Here are my thoughts on it, curious what everyone thinks - 

This module would take an optional parameter called `certificate_arn`. If NOT set, this module would create a single HTTP listener, and output its ARN as some value like `primary_alb_listener_arn` which could be used by individual applications to add listener rules/target groups to. If `certificate_arn` IS set, this module would create two listeners: an HTTP listener which is hardcoded to force-redirect to the HTTPS listener, and an HTTPS listener that uses `certificate_arn`. In this scenario, the value of `primary_alb_listener_arn` would be the ARN of the HTTPS listener instead, so that the listener rules point to the correct place.

This way it's easy for apps to initially configure themselves to work on HTTP, and then easily upgrade to HTTPS once their domain/certs are in place.

**Comment by dragonfleas** [comment]
Aaron and I had talked about potentially making a couple opinionated listener modules separate so we wouldn't be limited on listeners when trying to build root modules from these. For example: `terraform-aws-alb-http-listener` & `terraform-aws-alb-https-listener` with our standard configurations. I'm not opposed to including the listeners in this module itself and if we want to add more we could ALSO create modules for the listeners themselves. It just depends on how much we want to separate those concerns.

**Comment by chrisshiplet** [comment]
> I'm not opposed to including the listeners in this module itself and if we want to add more we could ALSO create modules for the listeners themselves
I like this, I think it's pretty much a guarantee that we're going to want AT LEAST a default HTTP listener on an ALB, so including them in here doesn't feel too tightly coupled to me. Then projects can always extend that in the rare scenario that they'd need something different. I'll wait till Aaron's back to make any changes so we can discuss it though.

**Comment by spruce-bruce** [comment]
👍🏼 
I do want to keep open the possibility of standardizing the use of codedeploy and making it easier through this or another module is key to that idea. I don't think that making decisions about that are super important enough to materially change this decision.
